### ISSUE TITLE
Gradle Tooling API dependency issue

### ISSUE THREAD

**Issue by mcdonnell-john** [lkishalmi/incubator-netbeans#6]
Normal `$ ant` build fails unless you have already have gradle-tooling-api-4.10.2.jar installed in your local maven repository.

**Steps to Reproduce**
1. Clean the local maven repository of the gradle api tooling files
2. Build the branch

**Expected Result**
Build completes successfully

**Actual Result**
Build fails with the following error:
`BUILD FAILED
/Users/john/codebase/incubator-netbeans/nbbuild/build.xml:125: Could not download 70A74F970B22AC1226F6A2983E38A77FA90E3BE9-gradle-tooling-api-4.10.2.jar from http://netbeans.osuosl.org/binaries/: java.io.IOException: Could not download 70A74F970B22AC1226F6A2983E38A77FA90E3BE9-gradle-tooling-api-4.10.2.jar to /Users/john/.hgexternalcache/70A74F970B22AC1226F6A2983E38A77FA90E3BE9-gradle-tooling-api-4.10.2.jar: java.io.IOException: Skipping download from http://central.maven.org/maven2/org/gradle/gradle-tooling-api/4.10.2/gradle-tooling-api-4.10.2.jar due to response code 404
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.doDownload(DownloadBinaries.java:249)
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.fillInFile(DownloadBinaries.java:190)
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.execute(DownloadBinaries.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: Skipping download from http://central.maven.org/maven2/org/gradle/gradle-tooling-api/4.10.2/gradle-tooling-api-4.10.2.jar due to response code 404
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.downloadFromServer(DownloadBinaries.java:275)
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.mavenFile(DownloadBinaries.java:177)
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.lambda$execute$0(DownloadBinaries.java:154)
	at org.netbeans.nbbuild.extlibs.DownloadBinaries.doDownload(DownloadBinaries.java:226)
	... 18 more`

**Impact**
Without fixing this issue a PR to Apache NetBeans will fail as Jenkins/Travis will be unable to local the correct jar.

Attempting to use `ant -q -Dbinary.server=https://jcenter.bintray.com/` also failed so I ended up downloading the jar from https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/4.10.2/ locally to my maven repo

**Comment by lkishalmi** [comment]
Well, to be seamless I set back to use OSUOSL for the gradle binary. It works now.
